ALTER TABLE device_patient
ALTER COLUMN assignment_date TYPE TIMESTAMP WITH TIME ZONE
USING assignment_date::TIMESTAMP WITH TIME ZONE,
ALTER COLUMN assignment_end_date TYPE TIMESTAMP WITH TIME ZONE
USING assignment_end_date::TIMESTAMP WITH TIME ZONE;

